### ISSUE TITLE
question/feature request: scale bar for plotPhyloTree

### ISSUE THREAD

**Issue by ajw2329** [Niinleslie/MesKit#192]
Hello,

First of all, thank you so much for this fantastic package!  I really like the visualizations and find the plotPhyloTree function produces much better looking trees than alternatives I have tried. I'm wondering - is there is any straightforward way to add a scale bar (helping provide a rough visual indication of #mutations per branch) to the phylo tree plots?  

Thanks very much!
Best,
Andrew

**Comment by Niinleslie** [comment]
Hi, @ajw2329, thanks for your interest in the package. We'll implement the scale bar in the plotPhyloTree function soon.

**Comment by Niinleslie** [comment]
In the latest version of MesKit, the scale bar can be added by setting `show.scale.bar = TRUE` in `plotPhyloTree()`.

**Comment by ajw2329** [comment]
Fantastic - thank you so much!
