### ISSUE TITLE
Cannot install on latest R 

### ISSUE THREAD

**Issue by juliewu-md** [Niinleslie/MesKit#211]
Hi I tried to install on R Studio 1.4.1103, R 4.0.3 but encountered the following error message:

BiocManager::install("MesKit")
Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.3 (2020-10-10)
Installing package(s) 'MesKit'
Warning message:
package ‘MesKit’ is not available for this version of R

Installing with devtools runs into a similar problem. Any advice?

**Comment by Wangxin555** [comment]
Hi,

Sorry for the delay in answering your question.
MesKit was released on the version 3.12 of Bioconductor, which matches R 4.0.3. So this problem would be solved after you update your Bioconductor to 3.12 and install MesKit by typing `BiocManager::install("MesKit")`.

Update your bioconductor:
`BiocManager::install(version = "3.12")`

**Comment by Niinleslie** [comment]
> Hi I tried to install on R Studio 1.4.1103, R 4.0.3 but encountered the following error message:
> 
> BiocManager::install("MesKit")
> Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.3 (2020-10-10)
> Installing package(s) 'MesKit'
> Warning message:
> package ‘MesKit’ is not available for this version of R
> 
> Installing with devtools runs into a similar problem. Any advice?

Hi,

Sorry for the delay in answering your question.
MesKit was released on the version 3.12 of Bioconductor, which matches R 4.0.3. So this problem would be solved after you update your Bioconductor to 3.12 and install MesKit by typing `BiocManager::install("MesKit").`

Update your bioconductor:
`BiocManager::install(version = "3.12")`

**Comment by juliewu-md** [comment]
Hi,

Thanks! That worked!

Julie
