### ISSUE TITLE
To do list 

### ISSUE THREAD

**Issue by likelet** [Niinleslie/MesKit#216]
- [x] Regist in  `scicrunch` and `bio.tools ` by @Wangxin555 
- [x] update the citation of Zheng Hu et al in documentation file by @Niinleslie

**Comment by Niinleslie** [comment]
- [x] Change GPL-v3 LICENSE by @Niinleslie 
- [x] Compare figSignatures() against deconstructSigs, MutationalPatterns and SignatureEstimation by @chenjy327 @Niinleslie 
- [x] Add a note in the vignette about "MOBSTER" for neutrality test" by @Niinleslie 
- [x] Make comparisons of different ways for constructing phylogenetic trees by @Niinleslie 
- [x] Make a detailed explanation about "merged CCF" and "CCF cutoff" by @Niinleslie 
- [x] Update triMutMatrix, fitSignatures, getPhyloTree for better understanding by @chenjy327 
- [x] Reanalyze HCC datasets using a new pipeline by @Niinleslie 
- [x] plotMutProfile(): not work properly when removeEmptyCols=`FALSE`  by @Wangxin555 
- [x] vafCluster(): (1)cluster CCFs (2)cluster VAFs of mutations in copy-neutral and LOH-free regions by @Niinleslie by @chenjy327
