### ISSUE TITLE
Error in f$acctran_traverse(tmp) : Not a matrix.

### ISSUE THREAD

**Issue by moshl** [Niinleslie/MesKit#244]
hi,Niinleslie
i meet a trouble when use Meskit::getPhyloTree。The NJ and ML method are ok, but The MP method is wrong for some patients. **getPhyloTree(maf_pt1, method="MP"),Error in f$acctran_traverse(tmp) : Not a matrix.**
So, Do you hava some advices?  Thanks.

bestwishes,
Mo

**Comment by likelet** [comment]
@moshl hi moshl, could you plz provide a  test dataset so that we can reproduce your error. 

sorry for the late reply

**Comment by likelet** [comment]
Closed due to a long-time inactive status.

**Comment by moshl** [comment]
> @moshl hi moshl, could you plz provide a test dataset so that we can reproduce your error.
> 
> sorry for the late reply

[sample18.zip](https://github.com/Niinleslie/MesKit/files/6390670/sample18.zip)

Looking forward your new reply. Thank you so much.

**Comment by likelet** [comment]
@moshl hi, we will check the data ASAP

**Comment by Niinleslie** [comment]
> > @moshl hi moshl, could you plz provide a test dataset so that we can reproduce your error.
> > sorry for the late reply
> 
> [sample18.zip](https://github.com/Niinleslie/MesKit/files/6390670/sample18.zip)
> 
> Looking forward your new reply. Thank you so much.



> > @moshl hi moshl, could you plz provide a test dataset so that we can reproduce your error.
> > sorry for the late reply
> 
> [sample18.zip](https://github.com/Niinleslie/MesKit/files/6390670/sample18.zip)
> 
> Looking forward your new reply. Thank you so much.

Hi moshl, 
It seems you used an old version of MesKit. We recommand you install the newest version and prepare input files following the documentation (http://meskit.renlab.org/), as many improvements have been made.
Feel free to contact use if you still have any questions.
