### ISSUE TITLE
Trouble shooting: Error when using plotPhyloTree function with parameter "MP"

### ISSUE THREAD

**Issue by Litdragen** [Niinleslie/MesKit#253]
Hi,

When I use the function plotPhyloTree with the method "MP", some samples report following error:

`Error in f$acctran_traverse(tmp) : Not a matrix`.

This problem can be solved by upgrading the depended package `phangorn` (v2.7.1)” 

best

**Comment by Niinleslie** [comment]
Thank you for posting this issue and solution.
