### ISSUE TITLE
How to map driver events to PhyloTree ?

### ISSUE THREAD

**Issue by qindan2008** [Niinleslie/MesKit#254]
How to map driver events to PhyloTree ?

Like this 

![image](https://user-images.githubusercontent.com/15100260/132487740-49ec66d7-585a-4cb0-a6fc-a0c682e4a5d5.png)

and this 

<img width="1269" alt="屏幕快照 2021-09-08 下午5 51 39" src="https://user-images.githubusercontent.com/15100260/132487950-88cfd4f4-272e-4a6f-9666-363a7fb3b54a.png">

Thank you very much.

**Comment by Niinleslie** [comment]
Hi, @qindan2008  
phyloTree@mut.branches(`Tree_Mut` column is RUE) presents mutations for each branch of the phylogenetic tree.

**Comment by likelet** [comment]
Closed due to long time inactivate
