### ISSUE TITLE
Error: Each row of output must be identified by a unique combination of keys.

### ISSUE THREAD

**Issue by sherryxuePKU** [Niinleslie/MesKit#256]
Hello~ I've encountered the problem "Error: Each row of output must be identified by a unique combination of keys." when running the command getPhyloTree. I succeeded in running the example data in this step, and the plotMutProfile with my own maf. I'd be grateful if any one have solution to this problem~

**Comment by likelet** [comment]
hi. can you plz provide more details related to your issue. For example, show your code as well as your dataset. Also with `Sessions()` information. 
Plz follow this issue and help.  @Niinleslie

**Comment by sherryxuePKU** [comment]
Sorry to bother you for the above question. I've found the problem that I had duplicated Tumor_Sample_Label. Btw, concerning to the function getPhyloTree(), I noticed that the tree is rooted to the "NORMAL" sample supplemented to the mutMatrix. What if users want to root the tree to their selected sample? And is "NORMAL" requested to be included in the Tumor_Sample_Label?

**Comment by Niinleslie** [comment]
Hi, "Normal sample" is not required in the MAF data. 
Generally, the root of a phylogenetic tree represents the normal sample that preceded the tumor. In this way, it is helpful to track the evolutionary trajectory of cancer progression and infer evolutionary relationship among tumor regions. Therefore, we do not recommend assigning other samples as the root.
